### PR TITLE
submitting about me 

### PR DESCRIPTION
**Pull request by PoChunYang**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
You forgot to replace title: “PoChunYang” and file path of image in the qmd file. Make sure you render before submitting.

**Comment by PoChunYang** [comment]
OK, so I have to pull the request, again right? 
Is it possible to change here?

**Review by SidharthSaluja — COMMENTED** [review]
Yep fix the changes in the same file and open a pull request.

**Review by SidharthSaluja — COMMENTED** [review]
Looks like you gave the image path correctly now but not sure why did you delete the PoChunYang.jpg from images folder. That needs to be present to display image. Please recommit with fixed changes

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
