### PR TITLE
Submitting challenge 1: transforming birds.csv data

### PR DESCRIPTION
**Pull request by gnaik20**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Are you sure you want to submit me .rmd file instead of .qmd file. Also the name of the file shouldn’t have space make it like Challenge1_Gauri_Naik.qmd.
- Date is missing in yaml header. 
 I also require freeze files. Render ur qmd file to generate _freeze files. 
 
 Do schedule a meeting in case of any problems

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks good just remove .rmd file and only keep .qmd file

**Review by SidharthSaluja — APPROVED** [review]
You are awsome!

**Comment by SidharthSaluja** [comment]
Oops I thought everything is correct but seems your didnt see your output  while rendering.
I am getting error of bird.csv not found. Could you please correct that and send again. 
Screenshot 2023-04-08 at 11 27 40 PM

**Comment by SidharthSaluja** [comment]
Add this data in the _data folder and send to me again. I am right now removing the submission until you fix it. I will wait for the correct version. Please let me know in case of help. Happy to help

**Comment by gnaik20** [comment]
Hello,I’ve committed the file again and fixed the file path. It rendered correctly for me; please let me know if the issue is fixed.Thank you for helping me,GauriOn Apr 9, 2023, at 1:34 AM, Sidharth Saluja ***@***.***> wrote:﻿
Add this data in the _data folder and send to me again. I am right now removing the submission until you fix it. I will wait for the correct version. Please let me know in case of help. Happy to help

**Pull request merged**
