### PR TITLE
Challenge 1 Freeze files

### PR DESCRIPTION
**Pull request by dirichiumunna**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I dont want _data folder to be modified. I am seeing a dot gitignore file which shouldn’t be present in data folder.

**Comment by dirichiumunna** [comment]
How can I rectify this? I probably tried to do something to create it, but let me know what to do to rectify

**Review by SidharthSaluja — COMMENTED** [review]
Please remove the .gitignore from _data folder. I think that would be enough.

**Comment by dirichiumunna** [comment]
I have deleted this!

**Comment by dirichiumunna** [comment]
Sorry: just adding that it is also on my commit

**Review by SidharthSaluja — APPROVED** [review]
Looks good

**Pull request merged**
