### PR TITLE
Adding about me page

### PR DESCRIPTION
**Pull request by LindaHumphrey**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I did specify that image path is missing in LindaHumphrey.qmd and please dont name image as Linda.H.jpeg (do instead Linda_H.jpeg)

**Comment by LindaHumphrey** [comment]
Hi,I did made some changes, sorry for the repetitive I have trouble integrating Rstudio and GitHub well. I have a meeting with one of the Tutors to clear out the confusion. I have things written well on Rstudio but when I get to GitHub I don’t think I am doing the right thing and I don’t seem to see the changes in GitHub appearing. RegardsLinda HumphreyOn Feb 21, 2023, at 1:44 PM, Sidharth Saluja ***@***.***> wrote:﻿
@SidharthSaluja commented on this pull request.

I did specify that image path is missing in LindaHumphrey.qmd and please dont name image as Linda.H.jpeg (do instead Linda_H.jpeg)

**Comment by SidharthSaluja** [comment]
Okay awesome. You are on the right track. Your files just needs some little modifications like image:images/Linda_H.jpeg like that in the qmd file. (Including renaming of file Linda.H.jpeg to Linda_H.jpeg). Slack me if still in confusion

**Comment by LindaHumphrey** [comment]
Do you have a min to jump on zoom? I honestly changed that image name not sure what’s not happening RegardsLinda HumphreyOn Feb 21, 2023, at 1:57 PM, Sidharth Saluja ***@***.***> wrote:﻿
Okay awesome. You are on the right track. Your files just needs some little modifications like image:images/{Linda_H.jpeg} like that in the qmd file. (Including renaming of file Linda.H.jpeg to Linda_H.jpeg). Slack me if still in confusion

**Comment by SidharthSaluja** [comment]
Yup can you slack or email me the zoom link. I can join. Or please provide your email so that I can create the meeting

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
