### PR TITLE
final

### PR DESCRIPTION
**Pull request by KhadijahAbdlRahman**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I dont need the rmd file. Is it necessary to submit?
posts/KhadijatAdeleye_ final.Rmd. Also it has space between file names. Please fix it

**Comment by SidharthSaluja** [comment]
The issue I mentioned is still not fixed. See your GitHub. It has those files please fix it

**Comment by SidharthSaluja** [comment]
Screenshot 2023-05-22 at 10 37 19 PM

**Comment by KhadijahAbdlRahman** [comment]
On Tue, 23 May 2023 at 12:37 AM, Sidharth Saluja ***@***.***>
wrote:

> [image: Screenshot 2023-05-22 at 10 37 19 PM]
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F67796130%2F240131428-b72abaae-f826-4b64-bc2f-e8f9bababe48.png&data=05%7C01%7Ckadeleye%40umass.edu%7C60bdbddd2c2b45ca4b3308db5b476faf%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638204134595184340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FMPmIoN03BZtvRkDIPmjz9REnKYBew0KHcJbmRTFZiE%3D&reserved=0>
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDACSS%2F601_Spring_2023%2Fpull%2F621%23issuecomment-1558507606&data=05%7C01%7Ckadeleye%40umass.edu%7C60bdbddd2c2b45ca4b3308db5b476faf%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638204134595184340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F1g%2Fjzrt7nNBrm7dWwtsR7q65CK68xILaCTaiL3AXw8%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA52YNC36UZQBG2D4KSI2ML3XHQ5JDANCNFSM6AAAAAAYK6R3XI&data=05%7C01%7Ckadeleye%40umass.edu%7C60bdbddd2c2b45ca4b3308db5b476faf%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638204134595184340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HWbEFE2DUOwP89djqZG%2B%2FC63Xcs4Y3VnPP%2FNjCVay28%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
What do I have to do

**Comment by SidharthSaluja** [comment]
I already wrote what you to do in above comment. Please read that - "I dont need the rmd file. Is it necessary to submit?"

**Comment by KhadijahAbdlRahman** [comment]
On Tue, 23 May 2023 at 12:39 AM, Sidharth Saluja ***@***.***>
wrote:

> I already wrote what you to do in above comment. Please read that - "I
> dont need the rmd file. Is it necessary to submit?"
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDACSS%2F601_Spring_2023%2Fpull%2F621%23issuecomment-1558508976&data=05%7C01%7Ckadeleye%40umass.edu%7C7a38d5e35d07423ad06b08db5b47b953%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638204135837409666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7GOkG0OryBAo%2FgGx%2BllzA7YngzW6akuWdyYLa3QkzZU%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA52YNC2K33EWX24XFBP3NVLXHQ5QZANCNFSM6AAAAAAYK6R3XI&data=05%7C01%7Ckadeleye%40umass.edu%7C7a38d5e35d07423ad06b08db5b47b953%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638204135837409666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X1ouzQijRsnIqBrGGjFyA6cp2sXEzkr5K6xFjpkPVPA%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
No I have deleted it

**Review by SidharthSaluja — COMMENTED** [review]
Nope you have not. I literally took a screenshot from your GitHub. Maybe you forgot to push the change to GitHub. Just doing change in R studio doesnt help. You need to tell GitHub that you are deleting the file. So in Git tab there would be a D mark on that file. You might have forgot to push it

**Review by SidharthSaluja — COMMENTED** [review]
Nope you have not. I literally took a screenshot from your GitHub. Maybe you forgot to push the change to GitHub. Just doing change in R studio doesnt help. You need to tell GitHub that you are deleting the file. So in Git tab there would be a D mark on that file. You might have forgot to push it

**Comment by KhadijahAbdlRahman** [comment]
Can i submit now

**Comment by SidharthSaluja** [comment]
Why you are waiting to submit? I would sleep soon lmao.

**Comment by SidharthSaluja** [comment]
Nope the change I mentioned in the comment hasn’t been fixed. Now you modified your final project. I may require freeze for that now. Can you check your GitHub from browser and then you can see what files are there in GitHub. Focus.. you just need to delete the mentioned file. It is not a big deal. In RStudio, you probably not pushing your deleted file change.

**Comment by KhadijahAbdlRahman** [comment]
Please what should I do now

**Comment by KhadijahAbdlRahman** [comment]
I have resubmitted it
Please check

**Comment by SidharthSaluja** [comment]
Nope, https://github.com/KhadijahAbdlRahman/601_Spring_2023/tree/template/posts

I said numerous times to check GitHub for what you submitting me

**Comment by KhadijahAbdlRahman** [comment]
Please check if its okay

**Review by SidharthSaluja — APPROVED** [review]
I knew it. You will do it :)

**Comment by KhadijahAbdlRahman** [comment]
is this okay

**Comment by KhadijahAbdlRahman** [comment]
hi Sidharth,

Is there anything I need to do?

**Pull request merged**
