### PR TITLE
Adding about me page

### PR DESCRIPTION
**Pull request by mgalarneau**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Looks like you already submitted the about me mage and it has been approved. May I know what pull request is this for since I see merge conflicts with previous submission

**Comment by mgalarneau** [comment]
@SidharthSaluja I was informed last Friday 2/10 that there was an issue with the initial setup of the github repo. It was fixed by removing the challenge instruction from the post folder in the template branch. However, since I made a pull request before this was fixed, I was instructed to delete/remove my course repository and the local files, and recreate a new repository from scratch, recreate a new RStudio project, rework the personal bio page, commit and submit pull request to the submission branch. So, I resubmitted my about me page. But if that is not necessary, you can disregard my request.

**Review by SidharthSaluja — APPROVED** [review]
Okay I removed your previous submission and added new one. Good work on it.

**Comment by mgalarneau** [comment]
@SidharthSaluja Thank you!

**Pull request merged**
