### PR TITLE
Submitting Challenge 4

### PR DESCRIPTION
**Pull request by timshores**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Need freeze files for challenge 5 too

**Comment by timshores** [comment]
Hi Sidharth, I haven't begun work on challenge 5, yet. I'm just syncing the file.

**Review by SidharthSaluja — COMMENTED** [review]
Then I guess you have to remove it from GitHub. Since I can see the file you sent me.

**Comment by timshores** [comment]
Is it possible to accept the file as it is now, and then accept the updated file when I submit a pull request later on?

**Review by SidharthSaluja — COMMENTED** [review]
Ummm I dont think I can do that since it could make our system slow for other students.
There are two choices
1) Add freeze files for challenge 5 and of course you can modify challenge 5 later and send me
2) Remove that from GitHub. I can help you in that in case you need help. I would just move that file somewhere safe and recommit to GitHub so that it gets deleted from GitHub

**Review by SidharthSaluja — APPROVED** [review]
All set.

**Pull request merged**
