### PR TITLE
commit ch 7 - edits

### PR DESCRIPTION
**Pull request by duffysueellen**
edits to challenge 7

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Need freeze files too since the challenge7 was modified

**Review by SidharthSaluja — APPROVED** [review]

**Comment by duffysueellen** [comment]
I'm not exactly sure why but my Ch 7 is not updating correctly onto the
course page.
It seems to be an older version, I removed the last graph and added a
different one.
Should I rename the file and try to submit again?

**Comment by SidharthSaluja** [comment]
Give it 5-10 min. Our GitHub action is still running

**Comment by duffysueellen** [comment]
Thank you! will do.

**Comment by SidharthSaluja** [comment]
Now you can see

**Comment by duffysueellen** [comment]
The final plot looks good now! But now there are 2 of the same plots

**Pull request merged**
