### PR TITLE
First Attempt to Commit Challenge 6

### PR DESCRIPTION
**Pull request by krissmole**

### CODE REVIEW

**Comment by dongericoyu** [comment]
Kris, can you change line#5 in your .qmd file from date: "04/05/23" to date: "04/05/2023" ? Just make sure the date format is correct. Save it, re-render, and resubmit a pull request.

**Comment by krissmole** [comment]
Will do.  Thanks.

Kris

**Comment by krissmole** [comment]
Just sendt second attempt....let me know if that went through ok......

Kris

**Comment by krissmole** [comment]
Great, thanks!

**Pull request merged**
