### PR TITLE
About Me Blog Post 

### PR DESCRIPTION
**Pull request by Sm1235**
I might have done this very wrong let me know if I really messed up.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I was wondering if you have sync the fork?

**Comment by SidharthSaluja** [comment]
Could you remove freeze folder and re-submit.

**Comment by Sm1235** [comment]
Yes I can try and sync my fork and deleting the freeze folder and then
resubmit

**Comment by SidharthSaluja** [comment]
Cool. Let’s close this pull request so that we don’t get any merge conflicts. On your end, please submit a new pull request.

**Pull request closed without merging**
