### PR TITLE
Challenge-6 freeze files and Project Proposal submission

### PR DESCRIPTION
**Pull request by SUSMITAMADINENI**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I dont think posts/final_project_assignment1_instructions&template.qmd is needed and can you delete the respective freeze file of it. It is causing merge conflict.

**Comment by SUSMITAMADINENI** [comment]
I have pushed it accidentally, I have deleted it now. Could you please try now? Thanks.

**Review by SidharthSaluja — COMMENTED** [review]
Could you delete the freeze files of that too _freeze/posts/final_project_assignment1_instructions&template/

**Comment by SUSMITAMADINENI** [comment]
I have deleted the freeze files also now. Can you please try now? Thanks.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
