### PR TITLE
First Weekly challenge blog post by shantanu patil

### PR DESCRIPTION
**Pull request by REDFOX1899**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Can you include freeze files too. Render your challenge qmd file in post folder to generate freeze files.

**Comment by REDFOX1899** [comment]
I uploaded the freeze files and challenge 1 now.

**Comment by SidharthSaluja** [comment]
Still cant see the freeze files. Did you push changes?

**Review by SidharthSaluja — COMMENTED** [review]
Still cant see Freeze folder in commits. Slack me or schedule an appointment in case you need help.

**Pull request closed without merging**
