### PR TITLE
Challenge 2 and 3

### PR DESCRIPTION
**Pull request by aritra1097**
I had committed challenges 2 and 3 before. But I am seeing the files and the freeze files in the git window again. That is why I committed them, but I do not know if I am doing the correct thing.

### CODE REVIEW

**Comment by aritra1097** [comment]
Please do not accept them. I had submitted challenge 3 before. But now, the file somehow has changed in my system, and is just showing me the question for challenge 3. I guess something is wrong.

**Review by SidharthSaluja — COMMENTED** [review]
yeah I also see ur answers removed. might want to copy paste them back. You can always see what files you changed in the pull request to correct the issue.

**Comment by SidharthSaluja** [comment]
Let me close this pull request so that I dont accept them

**Comment by aritra1097** [comment]
Thanks Sidhart!

**Pull request closed without merging**
