### PR TITLE
Submitting About Me Page

### PR DESCRIPTION
**Pull request by FnuAvineshKrishnan**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Can you revert the changes of about.qmd in root folder. This file should not be modified.
I would go to GitHub desktop and revert those changes of that file

**Comment by FnuAvineshKrishnan** [comment]
> Can you revert the changes of about.qmd in root folder. This file should not be modified.
> I would go to GitHub desktop and revert those changes of that file

I haven't made any changes to the about file in the root folder. The about.qmd is as it is, I have only added my own qmd in about folder. Please let me know what specific change I have to make

**Review by SidharthSaluja — COMMENTED** [review]
Screenshot 2023-05-13 at 5 53 06 PM

I can see there is extra line space. Hence file was modified.

Screenshot 2023-05-13 at 5 55 43 PM

It was modified 3 days ago.
Best way to go about is reverting from GitHub desktop. Now since you also did challenge 1, save your file somewhere safe in local and then revert so that you dont lose that challenge. Schedule a meeting if in trouble through calendly.

**Comment by FnuAvineshKrishnan** [comment]
I reverted the about.qmd file. Can you please check and update If everything's fine so that I can go ahead and submit the other challenges

**Review by SidharthSaluja — APPROVED** [review]
You are awsome!

**Comment by FnuAvineshKrishnan** [comment]
Thanks Sidharth. I have added Challenge 4 and 5 but they seem to be add into the same list of pull request after Challenge 3. Can you please let me know if they are merged too? Thanks

**Comment by SidharthSaluja** [comment]
Nope I didnt get request of challenge 4 and 5. You need to create a pull request for that

**Comment by FnuAvineshKrishnan** [comment]
Sorry, my bad. I committed both the challenges yesterday but forgot to create the pull request. Just created the pull request for the same.

**Pull request merged**
