### PR TITLE
Livia Charles Final Project Update

### PR DESCRIPTION
**Pull request by liviacharles**

### CODE REVIEW

**Review by SidharthSaluja — APPROVED** [review]
The post file and the freeze file doesnt align Bcs I should have received a freeze file of posts/Livia_Charles_final_project_update.qmd but didnt get that. But for the sake of less time I will approve it

**Comment by liviacharles** [comment]
Okay, thank you!
--
Livia Charles
M.S. Student in Geography
Department of Earth, Geographic, and Climate Sciences
University of Massachusetts Amherst
Phone: 707-889-6916
Email: ***@***.***

**Comment by SidharthSaluja** [comment]
I emailed you the correction that needs to be made. Please fix it and render your file to make sure everything is correct this time

**Comment by liviacharles** [comment]
I believe it should be fixed now.

Please let me know if I need to do anything else on my end.
--
Livia Charles
M.S. Student in Geography
Department of Earth, Geographic, and Climate Sciences
University of Massachusetts Amherst
Phone: 707-889-6916
Email: ***@***.***

**Pull request merged**
