### PR TITLE
Keith Martin Challenge 1 Submission

### PR DESCRIPTION
**Pull request by kmartin1096**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks fine except some names. I would like to see a better name for image. Name the image and update its path (like KeithMartin.jpeg instead of Headshot.jpg). I also in one of the qmd files Keith Martin_challenge1_Final.qmd - please dont include space between Keith Martin. Do it it like Keith_Martin_challenge1_Final.qmd.

**Comment by kmartin1096** [comment]
Do you need me to resubmit it with the new names?

**Review by SidharthSaluja — COMMENTED** [review]
Yep please do re-submit

**Comment by kmartin1096** [comment]
Re-uploading with new name.

**Pull request closed without merging**
