### PR TITLE
Final Project Submission

### PR DESCRIPTION
**Pull request by ravinabanz**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Rename your final as posts/601_RB_FinalProject_{Yourname}.qmd
Render your qmd file to generate freeze files. Also I didn’t need RB_data_files it is optional to delete them

**Comment by janani2001** [comment]
Hi I still didn't receive my grades for challenges and final project. Is there anything I still need to Submit?

**Comment by SidharthSaluja** [comment]
Yes i posted a comment above. You still didnt fix what i asked for.  How can i approve if you dont fix it😅. 

https://github.com/DACSS/601_Spring_2023/pull/670#pullrequestreview-1448320716

**Comment by SidharthSaluja** [comment]
I dont see any changes you did. I guess it forget to push on github

**Comment by janani2001** [comment]
I did again can you see now?

**Comment by SidharthSaluja** [comment]
Check your forked repo. If it has changes then you did submit me otherwise you did not. 

I dont see any changes currently

**Comment by janani2001** [comment]
"https://github.com/DACSS/601_Spring_2023/assets/64526603/984f3516-4626-4136-b06d-25f710e38828"
Here is the Screenshot. Under post I can see the changes. Do let me know If anything else i can do from my side.

**Comment by SidharthSaluja** [comment]
Oh wait you confused me. You wrote comment on Ravina post. I thought i had to see ravina post. Please from next time dont write comments on other students posts Janani. I will review yours if i see open pull request

**Comment by ravinabanz** [comment]
Hi Sidharth, I have made the changes that you asked for. Thanks

**Review by SidharthSaluja — COMMENTED** [review]
Remove posts/RB_data_files
Remove posts/temp_files
Remove posts/zip

**Review by SidharthSaluja — APPROVED** [review]
All set !

**Comment by SidharthSaluja** [comment]
I didnt know you were using the files in your bibliography. I thought it is external data like csv. Could you re-add those back? It must be in previous commits. Schedule/ Or slack me for help
Screenshot 2023-06-01 at 9 13 53 PM

**Pull request merged**
