### PR TITLE
Challenge 2 submission by Nanci Kopecky

### PR DESCRIPTION
**Pull request by nkopecky**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Were there two challenge files for challenge 2? I see two files in posts for challenge 2

**Comment by nkopecky** [comment]
Please just use the most recent one.

**Review by SidharthSaluja — COMMENTED** [review]
You need to delete on your end and send me correct pull request.

**Comment by nkopecky** [comment]
I am closing these requests

**Pull request closed without merging**
