### PR TITLE
Submitting challenge 1.

### PR DESCRIPTION
**Pull request by aritra1097**
Hi,

I was not being able to submit the first challenge, as it was not displaying after committing. I tried it thrice, and finally all of them appeared together. Could you please advice me on what to do?

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I can see your challenge files but you have unwanted files. Delete the ones you dont want and commit and send me pull request. Also I need freeze files, you can generate them by rendering the qmd file

**Comment by aritra1097** [comment]
Hi Siddhart,

Thank you.

I did it again. Please let me know if this is alright!

**Comment by aritra1097** [comment]
Something is wrong and it says that the qmd file is deleted. But I deleted
the other files, and pushed the new qmd file and the rendered freeze file.

Should I try it again?

**Review by SidharthSaluja — COMMENTED** [review]
I see two photos. Can you remove one photo.
Secondly, rename the photo. to Aritra_photo_re.jpg to avoid spaces between names.

Optional step to maybe avoid future problem - Delete freeze folder completely. Then render your posts/aritrabasu_challenge_1.qmd. This would generate new freeze files. Commit those freeze files rest of code.

**Review by SidharthSaluja — COMMENTED** [review]
Okay now just freeze files are missing. Render this qmd file. You should be able to generate freeze

**Review by SidharthSaluja — COMMENTED** [review]
do remember to change the path of image in qmd file too

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
