### PR TITLE
added about me details

### PR DESCRIPTION
**Pull request by Priyanka-Thatikonda**
added details about me for the first task

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
1. _templates should not be modified. Revert back change from GitHub desktop. 
2. In about folder name your file {Yourname}.qmd to avoid merge conflicts
3. Remove _freeze/posts/challenge2_instructions
4. Remove _freeze/posts/challenge1_instructions
5. Remove your image from root image folder. Only about/images/PriyankaThatikonda.jpeg is fine.
6. Need _freeze files for your challenges. Render your .qmd files in the post folder to generate _freeze files

**Comment by Priyanka-Thatikonda** [comment]
Hi Sidharth,

If i revert a change as per your comment - "_templates should not be
modified. Revert back change from GitHub desktop" - will all the changes i
made till now go back?

Kindly suggest what can be done since i have done 5 challenged after this.

Thanks.
PRIYANKA

**Review by SidharthSaluja — COMMENTED** [review]
Screenshot 2023-05-21 at 5 10 39 PM


Yup I can now need template file correction and freeze files of all the challenges in post folder

**Review by SidharthSaluja — COMMENTED** [review]
Freeze files are now file. _templates folder is still modified. Please revert it back

**Comment by SidharthSaluja** [comment]
Screenshot 2023-05-21 at 5 31 16 PM
See modified 2 hours ago

**Pull request closed without merging**
