### PR TITLE
Submitting Challenge 3

### PR DESCRIPTION
**Pull request by mgalarneau**
I would only like to merge challenge 3 if possible! Thank you

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Could you remove Challenge 1 instructions.R from posts folder. This seems unwanted file

**Comment by mgalarneau** [comment]
@SidharthSaluja challenge 1 instructions.R is deleted. Let me know if that worked

**Review by SidharthSaluja — COMMENTED** [review]
Now it looks like _quarto.yml is modified. It should not be modified.

**Comment by SidharthSaluja** [comment]
site-url: https://github.com/DACSS

this line should come but seems it is deleted.

**Comment by mgalarneau** [comment]
@SidharthSaluja Erico and I made that modification during a 1:1 in hopes to create a personal course blog for me as Prof. Rolfe showed us in one of our previous classes. I have replaced the modified file with the original version in my repo. I am seeking only to submit my challenge 3.

**Comment by SidharthSaluja** [comment]
Okay let me explain. Since _quarto.yml was written before by Professor. She only is allowed to change it. Removing the contents of the file and replacing the original context will make GitHub show that you have modified it. This would result in merge conflict. You can see this message of merge conflict at bottom too. The way to fix it would be. Reverting the change of _quarto.yml. The best way to do that is install GitHub desktop and go to history where you modified this file and just revert back changes. I can definitely help you. You can schedule a meeting with me or slack me. Just install GitHub desktop that would be pretty useful.

**Comment by SidharthSaluja** [comment]
Additional thing it is highly unrecommended to upload files via upload. _quarto.yml was added via uploads. It will bypasses our gitignore stuff. Just for future references.

**Review by SidharthSaluja — APPROVED** [review]
site-url: https://github.com/DACSS

should be there. But is is not in the file in _quarto.yml after title

**Comment by SidharthSaluja** [comment]
Mistakenly pressed approved. But once you fix this line, I can merge.

**Pull request closed without merging**
