### PR TITLE
Challenge 1

### PR DESCRIPTION
**Pull request by timshores**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
why it is shown that you modified wild_bird_data? Did you change something in it.

**Comment by timshores** [comment]
I opened wild_bird_data at some point to look at it via Excel. I didn't modify any data but I probably auto-saved a change column width without noticing that it saved. I tried to remove this from the commit, but I'm not sure how to do that.

**Review by SidharthSaluja — COMMENTED** [review]
In R studio, there would be a settings button to revert the change. I can help you in that. Please slack me or book appointment. Also include _freeze files for challenge 2.

**Comment by timshores** [comment]
Hi Sidharth, I reverted the commits with the wild_bird_data changes, then restored my two challenge in a final commit. Does this look like it fixes my problem?

**Review by SidharthSaluja — COMMENTED** [review]
Ummm no. Now this wild_bird_data.xlsx is deleted and gitignore is added. Please do call with me. I can try to help you for sure. We shouldn’t change/add .gitignore. What I feel instead of reverting the change, you clicked add to gitignore.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
