### PR TITLE
HW1 submission by Michele Carlin

### PR DESCRIPTION
**Pull request by MicheleCarlin**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Everything is fine. But please include freeze files too. To get freeze files, render your MicheleCarlin_hw1.qmd

**Comment by MicheleCarlin** [comment]
I had rendered the file earlier but I thought I erroneously sent freeze
files last week so I didn't include them this week.  Anyway, I just now
committed them but then when I try to push them, I am getting this error
message:

>>> C:/Users/CarlinML/AppData/Local/Programs/Git/bin/git.exe push origin HEAD:refs/heads/templateTo https://github.com/MicheleCarlin/601_Spring_2023.git
 ! [rejected]        HEAD -> template (fetch first)
error: failed to push some refs to
'https://github.com/MicheleCarlin/601_Spring_2023.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by MicheleCarlin** [comment]
I should have also mentioned that when I found out I had to send over
freeze files, I decided to add one more thing to my HW1 qmd file and was
attempting to commit that updated file so perhaps that is causing the
problem?!?

**Comment by SidharthSaluja** [comment]
Looks like a git issue. I can help you fix this. You can slack me. We can have call. If you want to schedule with tutors about git issue. You can make a formal appointment.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
