### PR TITLE
Final project submission. 

### PR DESCRIPTION
**Pull request by timshores**
Thank you for an excellent class and all of the professor and TA support! You all rocked it.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Can you delete file called Tasks.

**Comment by timshores** [comment]
done

**Review by SidharthSaluja — COMMENTED** [review]
Why delete you delete the freeze of your challenges 1to 7? I dont think it has to be deleted. I need them to run your challenges if you submitted me

**Review by SidharthSaluja — COMMENTED** [review]
I need them back. Render your challenge files

**Comment by timshores** [comment]
I've deleted the freeze folder a few times since you recommended I delete the freeze folder to troubleshoot an error.

I rendered all challenge files and pushed the commit.

**Review by SidharthSaluja — APPROVED** [review]
Okay much better

**Pull request merged**
