### PR TITLE
Submitting about me page

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Kindly submit all the work in submission branch (not template)

**Comment by SidharthSaluja** [comment]
Please don’t add submission in template branch

**Comment by ghost** [comment]
Hello, I think I will need some additional help with this. I went to change
something in my file and now when I try to commit it to github, nothing is
actually showing up in github.

Connor Landreth

**Comment by SidharthSaluja** [comment]
The best way to go about this is deleting this repo and cloning it again. There have been so many commits on this repo - troubleshooting this would be lengthy process.

**Comment by ghost** [comment]
Hello, the problem I keep running into is that I may delete the repo, but
then when I clone and go to commit again, all of the past commits reappear,
not just the updated ones I am looking to send.

Do I need to clear my git tab in rstudio? How do I go about transferring
only the desired qmd and jpg to the new cloned repo?

**Pull request closed without merging**
