### PR TITLE
Final Project Submitted by Janani Natarajan

### PR DESCRIPTION
**Pull request by janani2001**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Name your file FinalAssignment1_{Yourname}.qmd and render it again.

**Comment by janani2001** [comment]
Hi,
By mistake I continued my final project in my final Assignment 1 after
pushing. Can I rename it as the final project and continue in that.

**Comment by SidharthSaluja** [comment]
I need your name also in the file to avoid merge conflicts So FinalProject_{Yourname}.qmd. Please rename accordingly

**Comment by janani2001** [comment]
Final Project Submitted By Janani Natarajan

**Review by SidharthSaluja — COMMENTED** [review]
Can you remove FinalProject.qmd and _freeze/posts/Final_Assignment_1/execute-results/html.json

And render your posts/Final_Project_Janani_Natarajan.qmd (I didnt get the freeze files for this)

Note - I didnt mean the name of submission which you just changed lol. I meant in the files you have to change.

**Review by SidharthSaluja — COMMENTED** [review]
Remove Final_project.qmd too

**Comment by janani2001** [comment]
Freeze File added for final project

**Review by SidharthSaluja — APPROVED** [review]

**Comment by janani2001** [comment]
Hi,

I’m Janani Natarajan and I submitted my challenges and project from git hub
repo profile(janani2001)  I didn’t receive my grades yet? Is there
anything I need to do?

Thanks,
Janani

**Comment by SidharthSaluja** [comment]
Approved your request again but I dont see your graphs either. DO you need help in debugging your code??

**Comment by janani2001** [comment]
I sent as pdf to prof.. I still have few things to rectify I’ll resubmit
tomorrow.

Thanks,
janani

**Comment by SidharthSaluja** [comment]
Okay.

**Comment by janani2001** [comment]
Hi, Can I change the dataset from cars to movies without losing marks?
I feel i can do best with movies

**Pull request merged**
