### PR TITLE
Challenge 3 Submission

### PR DESCRIPTION
**Pull request by dirichiumunna**
Please approve

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I see posts/_data/organiceggpoultry.xls is modified. Can you revert that

**Comment by dirichiumunna** [comment]
Hi,

I have looked around and getting confused. How do I do this?

**Comment by SidharthSaluja** [comment]
I would just open GitHub desktop and look where that file have been changed. Then I would revert it. Please schedule an appointment with me if you need help to debug more or you can even slack me. 
Looks like it changed yesterday
Screenshot 2023-05-05 at 10 27 12 AM

**Review by SidharthSaluja — COMMENTED** [review]
Umm still the _data organiceggpoultry.xls file have been shown edited somehow

**Comment by dirichiumunna** [comment]
I will set an appointment for Monday, or if you have some time this weekend, please let me know, but I can wait until next week. I apologize

**Review by SidharthSaluja — COMMENTED** [review]
Monday works

**Pull request closed without merging**
