### PR TITLE
Submitting Challenge 1

### PR DESCRIPTION
**Pull request by duffysueellen**

### CODE REVIEW

**Comment by duffysueellen** [comment]
Sduffy is the most recent commit and the one I would like to submit. I did not know how to delete the other files

**Review by SidharthSaluja — COMMENTED** [review]
You can delete  the files 
1) manually from GitHub. Go on file and press delete option. Then when you work again press git pull from R studio
2) From R studio - you can delete the files and in the git window of R studio you will see a D mark. Select that and commit and push to GitHub

**Review by SidharthSaluja — COMMENTED** [review]
I didnt receive freeze files. But looks like you added a new in the posts folder. If you are not using that could you remove that. Also submit with the freeze files. Render your SDuffy_challenge_1.qmd to get freeze files. Looks like you also deleted challenge2_instructions from template not sure why.

**Comment by duffysueellen** [comment]
I accidentally started editing challenge2 instructions, but i kept the copy that i accidentally changed in that folder, just under a different name. 

I just went to render the SDuffy_challenge_1.qmd and this error message popped up 
"'ERROR: YAMLError: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 3, column 53:
     ...  date: "02/24/2023" format: html: toc: true code-fold: true"

**Review by SidharthSaluja — APPROVED** [review]
You can schedule appointment with any tutor to fix that issue. Everything looks fine to me for now so I would approve.

**Comment by duffysueellen** [comment]
Thank you for all of your detailed feedback. I really appreciate it. I will
schedule an appointment with a tutor

**Pull request merged**
