### PR TITLE
Final project assignment 1 submission

### PR DESCRIPTION
**Pull request by ecksteinm42**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Ummm Can state statistics.csv have no space like State_statistics.csv and similar for PopEsts PovState. It is good practice file name doesn’t have space. You might need to fix in the code too and render the qmd file and send me again.

**Comment by ecksteinm42** [comment]
Hi Sidarth,

Thanks for this feedback. Unfortunately, I get this error message when I
try to render my file (I also tried rendering again after making some other
changes but before removing the spaces from the dataset names and it still
claimed that the path does not exist, so the rename is not the cause.)
Oddly, in the RStudio interface itself, birds <-
read_xlsx("MattEckstein_FinalProjectData/PopEsts_ProvState_2021.02.05.xlsx")
does in fact read in the data successfully. Do you have any ideas as to why
the path would be good in the qmd file itself but not when rendering it?
Thanks.

[image: image.png]

Additionally, my Git connection seems to be offering me the opportunity to
commit the qmd file and datasets themselves but not the freeze files
associated with them. Do you have any advice for how I can address this?
Thanks.

[image: image.png]


Regards,
Matt

**Review by SidharthSaluja — COMMENTED** [review]
So Your data folder should be present in the post folder. It should be posts/MattEckstein_FinalProjectData. 
I can see image that you send me

**Review by SidharthSaluja — COMMENTED** [review]
Only the qmd file in the post folder would produce freeze files.
So any qmd file in post folder should have associated freeze file. You can confirm that by looking to freeze folder itself. 

If you wanna schedule meeting, I am happy to help you

**Comment by ecksteinm42** [comment]
Hi Sidharth,

Thank you very much! I moved the final project folder to be a subfolder of
the post folder. The render runs to completion now, but the rendered
webpage displays errors that seemingly stem from the paths of the birds and
states datasets not existing (though they run fine at these paths in
RStudio). Might it work once you've pulled everything to the DACSS 601
repository and the webpage itself really exists as opposed to just the
rendering, or is there something else I need to tinker with? Thanks.

Additionally, I just committed+pulled+pushed my new work, and it seems to
have been added to my existing pull request from 4/12 rather than becoming
something I can create a new pull request on the basis of. Please let me
know if this creates any issues on your end and if there's anything I can
do to address them.

Regards,
Matt

**Review by SidharthSaluja — COMMENTED** [review]
Delete the MattEckstein_finalProjectdata from root folder. I dont need that in root folder (in post folder it is good). If the code gives files not found while rendering it would give same error in main course blog too. 
 states <- read_csv("posts/MattEckstein_FinalProjectData/State_statistics.csv”)
I would remove the posts/ to make it  - read_csv("MattEckstein_FinalProjectData/State_statistics.csv”) and then try rendering. 

I would also set my working directory in r studio console as posts/ using setwd command as you say it works in R studio.

**Comment by SidharthSaluja** [comment]
Also I dont see any changes in the .qmd file in the posts folder. I assume you dont have any changes in the qmd files

**Comment by ecksteinm42** [comment]
Hi Sidharth,

Thanks. I reset my working directory to posts and rewrote the file paths
accordingly, though the render is still telling me the path does not exist.
Can you think of any other possible causes of the rendering issue? I can
book a slot on Calendly if you think that would be the most helpful way to
communicate about it.

Since I've now rewritten the file paths this morning, there are changes to
the .qmd file, but it sounds right that there might not have been any
changes as of yesterday afternoon.

Thanks,
Matt

**Review by SidharthSaluja — COMMENTED** [review]
Oh then we can have quick slack call on Monday. Just remind me on slack or you can always schedule through calendy. I will try my best to solve the issue

**Comment by ecksteinm42** [comment]
Thanks! I booked a slot at 2:15 today via Slack.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
